# Generated by Django 5.0.2 on 2024-02-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('stage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('location', models.TextField(help_text='Enter all address with GPS', null=True)),
                ('enrolled_class', models.CharField(blank=True, max_length=100, null=True)),
                ('f_fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's fullname")),
                ('f_occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Occupation ")),
                ('f_address', models.TextField(blank=True, null=True, verbose_name="Father's Address ")),
                ('f_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's phone number ")),
                ('f_alive', models.BooleanField(default=True, verbose_name='Is he alive')),
                ('m_fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's fullname")),
                ('m_occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's Occupation ")),
                ('m_address', models.TextField(blank=True, null=True, verbose_name="Mother's Address ")),
                ('m_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's phone number ")),
                ('m_alive', models.BooleanField(default=True, verbose_name='Is she alive')),
                ('g_fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name="Guardian's fullname")),
                ('g_occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name="Guardian's Occupation ")),
                ('g_address', models.TextField(blank=True, null=True, verbose_name="Guardian's Address ")),
                ('g_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name="Guardian's phone number ")),
                ('enrolled_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('formerschool', models.CharField(blank=True, help_text='Which school is he or her coming from', max_length=500, null=True, verbose_name='Former School')),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schooladmin.classs')),
            ],
        ),
    ]
