# Generated by Django 4.2.10 on 2024-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='students_pics/'),
        ),
    ]
